function plotSpectrogram( ...
        iq, ...
        sampleRate, ...
        centerFrequency, ...
        windowLength, ...
        overlapLength, ...
        nfft, ...
        titleText)
%plotSpectrogram Plot complete-capture and first-10-ms spectrograms.

    stftWindow = hann(windowLength, 'periodic');
    [spectrum, frequency, time] = spectrogram( ...
        iq, stftWindow, overlapLength, nfft, sampleRate, 'centered');

    expectedTimeBinCount = floor( ...
        (numel(iq) - windowLength) / ...
        (windowLength - overlapLength)) + 1;
    if ~isequal(size(spectrum), [nfft, expectedTimeBinCount])
        error('plotSpectrogram:UnexpectedSize', 'Unexpected STFT matrix size.');
    end

    powerSpectrum = abs(spectrum).^2;
    clear spectrum;
    % 10 * log10(时频图最大功率点 + 1)
    maximumPowerDB = 10 * log10(max(powerSpectrum(:)) + eps('single'));

    captureDuration = numel(iq) / sampleRate;
    renderSpectrogram( ...
        powerSpectrum, frequency, time, sampleRate, centerFrequency, ...
        [0, captureDuration], maximumPowerDB, titleText);

    detailEndTime = min(10e-3, captureDuration);
    detailTimeMask = time <= detailEndTime;
    if any(detailTimeMask)
        renderSpectrogram( ...
            powerSpectrum(:, detailTimeMask), ...
            frequency, time(detailTimeMask), sampleRate, centerFrequency, ...
            [0, detailEndTime], maximumPowerDB, ...
            [titleText ' - first 10 ms detail']);
    end
end

function renderSpectrogram( ...
        powerSpectrum, frequency, time, sampleRate, centerFrequency, ...
        timeLimits, maximumPowerDB, titleText)

    outputSize = 1024;
    outputFrequencyIndex = linspace( ...
        1, size(powerSpectrum, 1), outputSize);
    outputTimeIndex = linspace( ...
        1, size(powerSpectrum, 2), outputSize);
    [timeQuery, frequencyQuery] = meshgrid( ...
        outputTimeIndex, outputFrequencyIndex);
    displayPower = interp2( ...
        powerSpectrum, timeQuery, frequencyQuery, 'linear');

    displayFrequency = linspace( ...
        frequency(1), frequency(end), outputSize).' + centerFrequency;
    displayTime = linspace(time(1), time(end), outputSize);
    powerDB = 10 * log10(displayPower + eps('single'));

    figure;
    imagesc( ...
        displayFrequency / 1e9, displayTime * 1e3, powerDB.');
    axis xy;
    xlabel('Radio frequency / GHz');
    ylabel('Time / ms');
    title(titleText);
    colorbar;
    xlim([ ...
        centerFrequency - sampleRate / 2, ...
        centerFrequency + sampleRate / 2] / 1e9);
    ylim(timeLimits * 1e3);
    clim([maximumPowerDB - 60, maximumPowerDB]);
    grid on;
end
