function plotSpectrogram( ...
        iq, ...
        sampleRate, ...
        centerFrequency, ...
        windowLength, ...
        overlapLength, ...
        nfft, ...
        titleText)
%plotSpectrogram Plot the complete capture on a fixed 1024-by-1024 grid.

    stftWindow = hann(windowLength, 'periodic');

    [spectrum, frequency, time] = spectrogram( ...
        iq, ...
        stftWindow, ...
        overlapLength, ...
        nfft, ...
        sampleRate, ...
        'centered');

    expectedFrameCount = floor( ...
        (numel(iq) - windowLength) / ...
        (windowLength - overlapLength)) + 1;

    if ~isequal(size(spectrum), [nfft, expectedFrameCount])
        error( ...
            'plotSpectrogram:UnexpectedSize', ...
            'Unexpected STFT matrix size.');
    end

    powerSpectrum = abs(spectrum).^2;
    clear spectrum;

    outputSize = 1024;
    outputFrequencyIndex = linspace( ...
        1, size(powerSpectrum, 1), outputSize);
    outputTimeIndex = linspace( ...
        1, size(powerSpectrum, 2), outputSize);
    [timeQuery, frequencyQuery] = meshgrid( ...
        outputTimeIndex, outputFrequencyIndex);

    powerSpectrum = interp2( ...
        powerSpectrum, ...
        timeQuery, ...
        frequencyQuery, ...
        'linear');

    frequency = linspace(frequency(1), frequency(end), outputSize).';
    time = linspace(time(1), time(end), outputSize);
    powerDB = 10 * log10(powerSpectrum + eps('single'));

    radioFrequency = frequency + centerFrequency;

    figure;
    imagesc( ...
        radioFrequency / 1e9, ...
        time * 1e3, ...
        powerDB.');
    axis xy;

    xlabel('射频频率 / GHz');
    ylabel('时间 / ms');
    title(titleText);
    colorbar;

    xlim([ ...
        centerFrequency - sampleRate / 2, ...
        centerFrequency + sampleRate / 2] / 1e9);
    ylim([0, numel(iq) / sampleRate] * 1e3);

    powerUpperLimit = max(powerDB(:));
    clim([powerUpperLimit - 60, powerUpperLimit]);
    grid on;
end
