function [txSUWaveform, txExtSUWaveform, info] = ...
    runHEExtendedRangeScenario()
%runHEExtendedRangeScenario Compare HE-SU and upper-106-tone HE-EXT-SU.

    rng('shuffle');

    channelBandwidth = 'CBW20';
    apepLength = 1000;
    mcs = 0;
    guardInterval = 3.2;
    heLTFType = 4;
    oversamplingFactor = 5;

    cfgSU = wlanHESUConfig( ...
        'ChannelBandwidth', channelBandwidth, ...
        'ExtendedRange', false, ...
        'NumTransmitAntennas', 1, ...
        'NumSpaceTimeStreams', 1, ...
        'MCS', mcs, ...
        'ChannelCoding', 'LDPC', ...
        'APEPLength', apepLength, ...
        'GuardInterval', guardInterval, ...
        'HELTFType', heLTFType);

    cfgExtSU = wlanHESUConfig( ...
        'ChannelBandwidth', channelBandwidth, ...
        'ExtendedRange', true, ...
        'Upper106ToneRU', true, ...
        'NumTransmitAntennas', 1, ...
        'NumSpaceTimeStreams', 1, ...
        'MCS', mcs, ...
        'ChannelCoding', 'LDPC', ...
        'APEPLength', apepLength, ...
        'GuardInterval', guardInterval, ...
        'HELTFType', heLTFType);

    psduLengthSU = getPSDULength(cfgSU);
    psduLengthExtSU = getPSDULength(cfgExtSU);

    if psduLengthSU ~= psduLengthExtSU
        error( ...
            'runHEExtendedRangeScenario:PSDULengthMismatch', ...
            'HE-SU and HE-EXT-SU require different PSDU lengths.');
    end

    psdu = randi([0, 1], psduLengthSU * 8, 1, 'int8');
    txSUWaveform = wlanWaveformGenerator( ...
        psdu, cfgSU, 'OversamplingFactor', oversamplingFactor);
    txExtSUWaveform = wlanWaveformGenerator( ...
        psdu, cfgExtSU, 'OversamplingFactor', oversamplingFactor);

    sampleRate = wlanSampleRate( ...
        cfgExtSU, 'OversamplingFactor', oversamplingFactor);
    ofdmInfo = wlanHEOFDMInfo( ...
        'HE-Data', cfgExtSU, ...
        'OversamplingFactor', oversamplingFactor);
    fftLength = ofdmInfo.FFTLength;
    rbw = sampleRate / fftLength;

    indicesSU = wlanFieldIndices( ...
        cfgSU, 'OversamplingFactor', oversamplingFactor);
    indicesExtSU = wlanFieldIndices( ...
        cfgExtSU, 'OversamplingFactor', oversamplingFactor);
    comparisonEnd = min( ...
        double(indicesSU.LLTF(2)), ...
        double(indicesExtSU.LLTF(2)));

    suPreamblePower = mean( ...
        abs(txSUWaveform(1:comparisonEnd)).^2);
    extPreamblePower = mean( ...
        abs(txExtSUWaveform(1:comparisonEnd)).^2);
    preambleBoostDB = 10 * log10( ...
        extPreamblePower / suPreamblePower);

    dataStart = double(indicesExtSU.HEData(1));
    dataEnd = double(indicesExtSU.HEData(end));
    extData = txExtSUWaveform(dataStart:dataEnd);
    analysisWindow = hann(fftLength, 'periodic');

    [dataPSD, dataFrequency] = pwelch( ...
        extData, ...
        analysisWindow, ...
        fftLength / 2, ...
        fftLength, ...
        sampleRate, ...
        'centered');

    upperHalfPower = sum(dataPSD(dataFrequency > 0));
    lowerHalfPower = sum(dataPSD(dataFrequency < 0));
    dataUpperToLowerPowerDB = 10 * log10( ...
        upperHalfPower / lowerHalfPower);

    if abs(preambleBoostDB - 3) > 0.5
        error( ...
            'runHEExtendedRangeScenario:UnexpectedPreambleBoost', ...
            'Expected about 3 dB preamble boost, measured %.2f dB.', ...
            preambleBoostDB);
    end

    if dataUpperToLowerPowerDB < 6
        error( ...
            'runHEExtendedRangeScenario:UnexpectedRUOccupancy', ...
            ['Expected the upper half-band HE-Data power to exceed ' ...
             'the lower half by at least 6 dB, measured %.2f dB.'], ...
            dataUpperToLowerPowerDB);
    end

    plotExtendedRangeSpectrum( ...
        txExtSUWaveform, ...
        sampleRate, ...
        fftLength, ...
        indicesExtSU);
    plotPreamblePowerComparison( ...
        txSUWaveform, ...
        txExtSUWaveform, ...
        sampleRate, ...
        comparisonEnd);

    info.ScenarioType = 'heExtendedRangeSU';
    info.ScenarioTitle = ...
        'HE Extended-Range SU with Active Upper 106-Tone RU';
    info.SampleRate = sampleRate;
    info.RBW = rbw;
    info.FFTLength = fftLength;
    info.PSDULength = psduLengthSU;
    info.StandardPacketFormat = packetFormat(cfgSU);
    info.ExtendedPacketFormat = packetFormat(cfgExtSU);
    info.ExtendedRange = cfgExtSU.ExtendedRange;
    info.Upper106ToneRU = cfgExtSU.Upper106ToneRU;
    info.StandardWaveformLength = numel(txSUWaveform);
    info.ExtendedWaveformLength = numel(txExtSUWaveform);
    info.StandardFieldIndices = indicesSU;
    info.ExtendedFieldIndices = indicesExtSU;
    info.PreambleBoostDB = preambleBoostDB;
    info.DataUpperToLowerPowerDB = dataUpperToLowerPowerDB;
    info.StandardConfig = cfgSU;
    info.ExtendedConfig = cfgExtSU;

    fprintf('\nHE Extended-Range Single-User 场景\n');
    fprintf('采样率：%.2f MHz\n', sampleRate / 1e6);
    fprintf('标准 HE-SU 样本数：%d\n', numel(txSUWaveform));
    fprintf('HE-EXT-SU 样本数：%d\n', numel(txExtSUWaveform));
    fprintf('L-STF/L-LTF 功率增强：%.2f dB\n', preambleBoostDB);
    fprintf('HE-Data 上/下半带功率比：%.2f dB\n', ...
        dataUpperToLowerPowerDB);
end

function plotExtendedRangeSpectrum( ...
        waveform, sampleRate, fftLength, fieldIndices)

    analysisWindow = hann(fftLength, 'periodic');
    overlapLength = 3 * fftLength / 4;

    [packetPSD, packetFrequency] = pwelch( ...
        waveform, ...
        analysisWindow, ...
        fftLength / 2, ...
        fftLength, ...
        sampleRate, ...
        'centered');

    [spectrum, frequency, time] = spectrogram( ...
        waveform, ...
        analysisWindow, ...
        overlapLength, ...
        fftLength, ...
        sampleRate, ...
        'centered');

    figure;
    tiledlayout(2, 1);

    nexttile;
    plot( ...
        packetFrequency / 1e6, ...
        10 * log10(packetPSD + eps));
    grid on;
    xlim([-sampleRate / 2, sampleRate / 2] / 1e6);
    xlabel('基带频率 / MHz');
    ylabel('功率谱密度 / dB/Hz');
    title('HE-EXT-SU 平均功率谱');

    nexttile;
    imagesc( ...
        time * 1e6, ...
        frequency / 1e6, ...
        10 * log10(abs(spectrum).^2 + eps));
    axis xy;
    hold on;

    dataStartTime = ...
        (double(fieldIndices.HEData(1)) - 1) / sampleRate * 1e6;
    dataEndTime = ...
        (double(fieldIndices.HEData(end)) - 1) / sampleRate * 1e6;
    xline(dataStartTime, '--w', 'HE-Data 开始');
    xline(dataEndTime, '--w', 'HE-Data 结束');

    ylim([-sampleRate / 2, sampleRate / 2] / 1e6);
    xlabel('时间 / μs');
    ylabel('基带频率 / MHz');
    title('HE-EXT-SU 时频图：数据占用上 106-tone RU');
    colorbar;
    colormap turbo;
end

function plotPreamblePowerComparison( ...
        suWaveform, extSUWaveform, sampleRate, comparisonEnd)

    movingAverageLength = round(sampleRate * 1e-6);
    time = (0:comparisonEnd - 1) / sampleRate * 1e6;

    figure;
    plot( ...
        time, ...
        20 * log10(movmean( ...
            abs(suWaveform(1:comparisonEnd)), ...
            movingAverageLength) + eps), ...
        '-b');
    hold on;
    plot( ...
        time, ...
        20 * log10(movmean( ...
            abs(extSUWaveform(1:comparisonEnd)), ...
            movingAverageLength) + eps), ...
        '-r');
    grid on;
    title('L-STF 和 L-LTF 功率（1 μs 移动平均）');
    xlabel('时间 / μs');
    ylabel('功率 / dBW');
    legend( ...
        'HE-SU', ...
        'HE Extended-Range SU', ...
        'Location', ...
        'southwest');
end
